[lift]
name = "roboto-agent"
description = "Roboto Agent"
platforms = ["linux-aarch64", "linux-x86_64", "macos-aarch64", "macos-x86_64"]

[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20251209"
version = "3.13.11"
lazy = true

[[lift.files]]
name = ":upload-agent"

[[lift.commands]]
exe = "#{cpython:python}"
args = ["{:upload-agent}"]
